-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 15:01:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafe_prosa_marcio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cafe_prosa_marcio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafe_prosa_marcio` DEFAULT CHARACTER SET utf8 ;
USE `cafe_prosa_marcio` ;

-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login_date` DATETIME NOT NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id`, `id_users`),
  INDEX `fk_login_history_users_idx` (`id_users` ASC) VISIBLE,
  CONSTRAINT `fk_login_history_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `cafe_prosa_marcio`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `cep` VARCHAR(8) NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `categoria_descr` VARCHAR(255) NOT NULL,
  `pontoref` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_address_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa_marcio`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(150) NOT NULL,
  `qtde_stock` VARCHAR(50) NOT NULL,
  `price_purchase` VARCHAR(150) NOT NULL,
  `price_sale` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`effective_product_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`effective_product_sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `data_venda` DATETIME NOT NULL,
  `qtde_produto` INT NOT NULL,
  `final_price_product` DECIMAL(10,2) NOT NULL,
  `price_product` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_effective_sale_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_effective_sale_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_effective_sale_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa_marcio`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effective_sale_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `cafe_prosa_marcio`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_value` DECIMAL(10,2) NOT NULL,
  `id_effective_product_sale` INT NOT NULL,
  `payment_description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`, `id_effective_product_sale`),
  INDEX `fk_payment_effective_product_sale1_idx` (`id_effective_product_sale` ASC) VISIBLE,
  CONSTRAINT `fk_payment_effective_product_sale1`
    FOREIGN KEY (`id_effective_product_sale`)
    REFERENCES `cafe_prosa_marcio`.`effective_product_sale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa_marcio`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa_marcio`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `data_venda` DATETIME NOT NULL,
  `qtde_produto` INT NOT NULL,
  `final_price_product` DECIMAL(10,2) NOT NULL,
  `price_product` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_effective_sale_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_effective_sale_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_effective_sale_users10`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa_marcio`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effective_sale_products10`
    FOREIGN KEY (`products_id`)
    REFERENCES `cafe_prosa_marcio`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
