-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 13:36:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cafe_prosa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cafe_prosa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cafe_prosa` DEFAULT CHARACTER SET utf8 ;
USE `cafe_prosa` ;

-- -----------------------------------------------------
-- Table `cafe_prosa`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login_date` DATETIME NOT NULL,
  `id_users` INT NOT NULL,
  PRIMARY KEY (`id`, `id_users`),
  INDEX `fk_login_history_users_idx` (`id_users` ASC) VISIBLE,
  CONSTRAINT `fk_login_history_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `cafe_prosa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(10) NULL,
  `cep` VARCHAR(8) NULL,
  `users_id` INT NOT NULL,
  `cidade` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `ponto_ref` VARCHAR(255) NULL,
  `category_add` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_address_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_address_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(150) NOT NULL,
  `qtde_stock` VARCHAR(50) NOT NULL,
  `price_purchase` VARCHAR(150) NOT NULL,
  `price_sale` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(150) NOT NULL,
  `qtde` VARCHAR(50) NOT NULL,
  `purchase_date` DATE NOT NULL,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_cart_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_cart_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `cafe_prosa`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`effective_product_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`effective_product_sale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_form` VARCHAR(150) NOT NULL,
  `final_price` DECIMAL(10,2) NOT NULL,
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `qtde_produto` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `data_venda` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `products_id`),
  INDEX `fk_effective_sale_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_effective_sale_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_effective_sale_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cafe_prosa`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_effective_sale_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `cafe_prosa`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cafe_prosa`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cafe_prosa`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_value` DECIMAL(10,2) NOT NULL,
  `effective_product_sale_id` INT NOT NULL,
  `effective_product_sale_users_id` INT NOT NULL,
  `effective_product_sale_products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `effective_product_sale_id`, `effective_product_sale_users_id`, `effective_product_sale_products_id`),
  INDEX `fk_payment_effective_product_sale1_idx` (`effective_product_sale_id` ASC, `effective_product_sale_users_id` ASC, `effective_product_sale_products_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_effective_product_sale1`
    FOREIGN KEY (`effective_product_sale_id` , `effective_product_sale_users_id` , `effective_product_sale_products_id`)
    REFERENCES `cafe_prosa`.`effective_product_sale` (`id` , `users_id` , `products_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
