-- MySQL Script generated by MySQL Workbench
-- Fri Nov  7 15:33:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lojinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lojinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lojinha` DEFAULT CHARACTER SET utf8 ;
USE `Lojinha` ;

-- -----------------------------------------------------
-- Table `Lojinha`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lojinha`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lojinha`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lojinha`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lojinha`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lojinha`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `validity` DATETIME NULL,
  `mark` VARCHAR(255) NULL,
  `weight` DOUBLE NULL,
  `category` VARCHAR(255) NULL,
  `model` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lojinha`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lojinha`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` CHAR(1) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `movimentdate` DATETIME NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`, `products_id`),
  INDEX `fk_stock_products_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_stock_products`
    FOREIGN KEY (`products_id`)
    REFERENCES `Lojinha`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
