-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 14:54:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Custodio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Custodio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Custodio` DEFAULT CHARACTER SET utf8 ;
USE `Custodio` ;

-- -----------------------------------------------------
-- Table `Custodio`.`Tipos-Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Tipos-Treino` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Empresas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Numero` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Codigo-acesso` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Usuarios` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Idade` VARCHAR(45) NULL,
  `Altura` VARCHAR(45) NULL,
  `Peso` VARCHAR(45) NULL,
  `Sexo` VARCHAR(45) NULL,
  `Empresas_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Empresas_ID`),
  INDEX `fk_Usuarios_Empresas1_idx` (`Empresas_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Empresas1`
    FOREIGN KEY (`Empresas_ID`)
    REFERENCES `Custodio`.`Empresas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Treinos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATA` VARCHAR(255) NULL,
  `Usuarios_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuarios_ID`),
  INDEX `fk_Treinos_Usuarios1_idx` (`Usuarios_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Treinos_Usuarios1`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `Custodio`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Academias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Academias` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Rua` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Numero` VARCHAR(45) NULL,
  `CEP` VARCHAR(45) NULL,
  `CIdade` VARCHAR(45) NULL,
  `Avaliacoes` VARCHAR(45) NULL,
  `Aulas` VARCHAR(45) NULL,
  `Horario` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Objetivos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Usuarios_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuarios_ID`),
  INDEX `fk_Objetivos_Usuarios1_idx` (`Usuarios_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Objetivos_Usuarios1`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `Custodio`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`CheckIn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`CheckIn` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Data` VARCHAR(45) NULL,
  `Usuarios_ID` INT NOT NULL,
  `Academias_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Usuarios_ID`, `Academias_ID`),
  INDEX `fk_CheckIn_Usuarios1_idx` (`Usuarios_ID` ASC) VISIBLE,
  INDEX `fk_CheckIn_Academias1_idx` (`Academias_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CheckIn_Usuarios1`
    FOREIGN KEY (`Usuarios_ID`)
    REFERENCES `Custodio`.`Usuarios` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIn_Academias1`
    FOREIGN KEY (`Academias_ID`)
    REFERENCES `Custodio`.`Academias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Tipos-Treino_has_Treinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Tipos-Treino_has_Treinos` (
  `Tipos-Treino_ID` INT NOT NULL,
  `Treinos_ID` INT NOT NULL,
  PRIMARY KEY (`Tipos-Treino_ID`, `Treinos_ID`),
  INDEX `fk_Tipos-Treino_has_Treinos_Treinos1_idx` (`Treinos_ID` ASC) VISIBLE,
  INDEX `fk_Tipos-Treino_has_Treinos_Tipos-Treino_idx` (`Tipos-Treino_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tipos-Treino_has_Treinos_Tipos-Treino`
    FOREIGN KEY (`Tipos-Treino_ID`)
    REFERENCES `Custodio`.`Tipos-Treino` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipos-Treino_has_Treinos_Treinos1`
    FOREIGN KEY (`Treinos_ID`)
    REFERENCES `Custodio`.`Treinos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Custodio`.`Academias_has_Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Custodio`.`Academias_has_Empresas` (
  `Academias_ID` INT NOT NULL,
  `Empresas_ID` INT NOT NULL,
  PRIMARY KEY (`Academias_ID`, `Empresas_ID`),
  INDEX `fk_Academias_has_Empresas_Empresas1_idx` (`Empresas_ID` ASC) VISIBLE,
  INDEX `fk_Academias_has_Empresas_Academias1_idx` (`Academias_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Academias_has_Empresas_Academias1`
    FOREIGN KEY (`Academias_ID`)
    REFERENCES `Custodio`.`Academias` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academias_has_Empresas_Empresas1`
    FOREIGN KEY (`Empresas_ID`)
    REFERENCES `Custodio`.`Empresas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
