-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 08:17:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema de Controle de Materiais de Escritório
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sistema de Controle de Materiais de Escritório
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema de Controle de Materiais de Escritório` DEFAULT CHARACTER SET utf8 ;
USE `Sistema de Controle de Materiais de Escritório` ;

-- -----------------------------------------------------
-- Table `Sistema de Controle de Materiais de Escritório`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema de Controle de Materiais de Escritório`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cargo` ENUM("colaborador", "administrador") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema de Controle de Materiais de Escritório`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sistema de Controle de Materiais de Escritório`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `marca` VARCHAR(255) NOT NULL,
  `categoria` VARCHAR(255) NOT NULL,
  `qntd_min` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
